# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OMNITIRX.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1195, 592)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -40, 1221, 671))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../jarvis/gifs/G.U.I Material/B.G/Black_Template.jpg"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(210, -30, 681, 671))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../jarvis/gifs/G.U.I Material/VoiceReg/Siri.gif"))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(860, -30, 501, 341))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../jarvis/gifs/G.U.I Material/ExtraGui/Earth.gif"))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 410, 371, 181))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("../jarvis/gifs/G.U.I Material/ExtraGui/Code_Template.gif"))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 30, 251, 41))
        self.label_5.setStyleSheet("color :rgb(38, 209, 50);\n"
"background-color : trancpeternt ;\n"
"font: 75 28pt \"Arial\";")
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(480, 500, 101, 31))
        self.pushButton.setStyleSheet("color: rgb(39, 207, 51);\n"
"font: 75 12pt \"8514oem\";\n"
"\n"
"background-color : trancperent;\n"
"border : 2px solid green;\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(600, 500, 101, 31))
        self.pushButton_2.setStyleSheet("color: rgb(39, 207, 51);\n"
"font: 75 12pt \"8514oem\";\n"
"\n"
"background-color : trancperent;\n"
"border : 2px solid green;\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(910, 290, 256, 61))
        self.textBrowser.setStyleSheet("color : rgb(55, 203, 60);\n"
"background-color : trancperent ;\n"
"font: 75 12pt \"8514oem\";\n"
"border : 2px solid green;")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(910, 370, 256, 61))
        self.textBrowser_2.setStyleSheet("color : rgb(55, 203, 60);\n"
"background-color : trancperent ;\n"
"font: 75 12pt \"8514oem\";\n"
"border : 2px solid green;")
        self.textBrowser_2.setObjectName("textBrowser_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_5.setText(_translate("MainWindow", "OMNITIRX"))
        self.pushButton.setText(_translate("MainWindow", "START"))
        self.pushButton_2.setText(_translate("MainWindow", "STOP"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
